version: '3'

services: 
  app:
    build: . # jรก pega a image do dockerfile
    entrypoint: dockersize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes: 
      - .:/home/node/app
    depends_on: 
      - db
    extra_hosts:
      - 'host.docker.internal:172:17:01' 